# Generated by Django 5.0.7 on 2024-08-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_remove_menu_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Maharashtrian Dishes'), (2, 'SouthIndian Dishes'), (3, 'Gujarati Dishes'), (4, 'Chinese Dishes'), (5, 'Sweets'), (6, 'Non-veg Foods')], verbose_name='Categorynsi'),
        ),
    ]
